██████╗░░█████╗░██████╗░░█████╗░<br>
██╔══██╗██╔══██╗██╔══██╗██╔══██╗<br>
██████╦╝███████║██████╦╝███████║<br>
██╔══██╗██╔══██║██╔══██╗██╔══██║<br>
██████╦╝██║░░██║██████╦╝██║░░██║<br>
╚═════╝░╚═╝░░╚═╝╚═════╝░╚═╝░░╚═╝<br>
✾●●✦WELLCOM TO BABA KHATRA✦●●✾<br>
❍❍❍❍❍❍❍❍✬✥✬❍❍❍❍❍❍❍❍<br>
៚CREATED BY : BABA KHATRAツ<br>
៚FACEBOOK : https://www.facebook.com/RE4L.H4CK3R<br>
៚COUNTRY : NEPAL⚒⚒<br>
៚✮✦NEPALI HACKER✦✮<br>
៚DESIGNER⚒RAHUL MISHRA<br>
៚ⓓⓞⓝⓣ ⓒⓞⓟⓨ ⓜⓨ ⓢⓒⓡⓘⓟⓣ<br>
❍❍❍❍❍❍❍❍✬✥✬❍❍❍❍❍❍❍❍<br>
✾●●✦WELLCOM TO BABA KHATRA✦●●✾<br>
❍❍❍❍❍❍❍❍✬✥✬❍❍❍❍❍❍❍❍
